#!/bin/sh
set -e

if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi

if [ "$1" = "configure" ] && [ -x "`which update-mime 2>/dev/null`" ]; then
	update-mime
fi

if [ "$1" = "configure" ] && which update-desktop-database >/dev/null 2>&1 ; then
	update-desktop-database -q
fi

if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/hicolor
fi
